# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Report generator ', kernelModule='plugin', kernelFunction='extractor_function', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgTabBook(name='TabBook_1', p='DialogBox', layout='0')
RsgTabItem(name='TabItem_1', p='TabBook_1', text='Basics')
RsgTextField(p='TabItem_1', fieldType='String', ncols=12, labelText='ODB directory path:', keyword='odb_dir_path', default='')
RsgTextField(p='TabItem_1', fieldType='String', ncols=12, labelText='Step:', keyword='step_name', default='')
RsgTextField(p='TabItem_1', fieldType='String', ncols=12, labelText='Frames:', keyword='frames', default='')
RsgTextField(p='TabItem_1', fieldType='String', ncols=12, labelText='Path to save results:', keyword='results_dir_path', default='')
RsgTextField(p='TabItem_1', fieldType='String', ncols=12, labelText='Results directory name:', keyword='results_dir_name', default='')
RsgCheckButton(p='TabItem_1', text='Include mesh data', keyword='include_mesh_data', default=False)
RsgCheckButton(p='TabItem_1', text='Export to csv', keyword='export_to_csv', default=False)
RsgCheckButton(p='TabItem_1', text='Take model screenshots', keyword='take_model_screenshots', default=False)
RsgTabItem(name='TabItem_3', p='TabBook_1', text='CSV Export')
RsgGroupBox(name='GroupBox_2', p='TabItem_3', text='I', layout='0')
RsgTextField(p='GroupBox_2', fieldType='String', ncols=12, labelText='Field output names:', keyword='field_output_names', default='')
RsgTextField(p='GroupBox_2', fieldType='String', ncols=12, labelText='Set name:', keyword='set_name', default='')
RsgTextField(p='GroupBox_2', fieldType='String', ncols=12, labelText='Instance name:', keyword='instance_name', default='')
RsgTextField(p='GroupBox_2', fieldType='String', ncols=12, labelText='Instance set name:', keyword='instance_set_name', default='')
RsgGroupBox(name='GroupBox_1', p='TabItem_3', text='II', layout='0')
RsgTextField(p='GroupBox_1', fieldType='String', ncols=12, labelText='Field output:', keyword='field_output', default='')
RsgTextField(p='GroupBox_1', fieldType='String', ncols=12, labelText='Value:', keyword='value', default='')
RsgTextField(p='GroupBox_1', fieldType='String', ncols=12, labelText='Minimum:', keyword='minimum', default='')
RsgTextField(p='GroupBox_1', fieldType='String', ncols=12, labelText='Maximum:', keyword='maximum', default='')
RsgTabItem(name='TabItem_2', p='TabBook_1', text='Screenshots')
RsgTextField(p='TabItem_2', fieldType='String', ncols=12, labelText='Views', keyword='view_names', default='')
RsgTextField(p='TabItem_2', fieldType='String', ncols=12, labelText='Field output display variables:', keyword='fo_disp_vars', default='')
RsgComboBox(name='ComboBox_1', p='TabItem_2', text='Items to display:', keyword='item_type', default='', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_1', text='Parts')
RsgListItem(p='ComboBox_1', text='Elements')
RsgListItem(p='ComboBox_1', text='Nodes?')
RsgListItem(p='ComboBox_1', text='Surfaces')
RsgTextField(p='TabItem_2', fieldType='String', ncols=12, labelText='Names of items to display:', keyword='item_names', default='')
RsgTextField(p='TabItem_2', fieldType='String', ncols=12, labelText='Contour plot limits?:', keyword='contour_plot_limits', default='')
dialogBox.show()